name: 'Publish an extension on Firefox Addons Store'
description: 'Deploy your WebExtension to Firefox Addons'
author: 'cardinalby'
inputs:
  uploadId:
    description: 'Id of already existing upload'
    required: false
  zipFilePath:
    description: 'Path to zip with packed WebExtension directory'
    required: false
  sourcesZipFilePath:
    description: 'Path to zip with sources of the addon'
    required: false
  extensionId:
    description: 'Id of extension which was already uploaded to Firefox Addons'
    required: true
  channel:
    description: 'The version channel, which determines its visibility on the site. Can be either "unlisted" or "listed"'
    required: false
    default: 'listed'
  jwtIssuer:
    description: 'JWT issuer also called "apiKey" obtained from created credentials'
    required: true
  jwtSecret:
    description: 'JWT secret also called "apiSecret" obtained from created credentials'
    required: true
  timeoutMs:
    description: 'Timeout in milliseconds of waiting of uploaded extension processing by Addons server'
    required: false
    default: '600000' # 10 min
outputs:
  errorUploadId:
    description: "id of upload"
  errorExtensionVersion:
    description: "extension version"
  sameVersionAlreadyUploadedError:
    description: "true if failed because the version was already uploaded"
  validationError:
    description: "true if failed because Add-ons validation rejected the extension"
  unauthorizedError:
    description: "true if failed because of 401 Unauthorized response from API"
  timeoutError:
    description: "true if failed because polling timed out according to timeoutMs input"
  requestThrottledError:
    description: "true if failed because request to Add-ons API has been throttled by the server"
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'package'
